### ISSUE TITLE
Full HTML5 Support Option

### ISSUE THREAD

**Issue by JyeGuru** [JustOff/cpf-update-win#2]
As mentioned here: http://chromium.woolyss.com/#html5-audio-video

Suggest the following:
- Option to replace `ffmpegsumo.dll` from Canary.zip if Flash update is being performed (since it's downloaded anyway?)
- Option to download Canary specifically to update `ffmpegsumo.dll` if both Chromium is updated and flash is NOT being updated.

I tried to get this to work my messing with the script a little today, but wasn't able to get it to function well enough to commit and pull request.

**Comment by JustOff** [comment]
As I have [previously noted](http://chromium.woolyss.com/?all=1#comment-423) "in my experience, even if substitution of ffmpegsumo.dll works on especially prepared test pages, in the wild world web it's mostly useless and we can't rely on this trick". So I'm not sure I want to complicate script by adding options until something changes.
