### ISSUE TITLE
question: PepperFlash portable or not?

### ISSUE THREAD

**Issue by Nuvolarix** [JustOff/cpf-update-win#3]
Hi there, first of all thanks for your great job about X-Chromium update! First time I used it today by upgrading successfully from 45.x to 48.x

Just a question, a little suggestion and perhaps a very little issue (I open this topic only, let me know if I should rather separate them):

1) - question - I'm wondering if PepperFlash check and update is about the system and is not portable, cause my previous chromium version had the pepperflash.dll (inside chrome\plugins folder), after using the script it says I already have the latest flash version (I guess in the system) and the chrome\plugins folder is now empty; I would really like a "portable" flash upgrade, all in all X-Chromium is portable too :-)

2) - small suggestion - I noticed a "VERSION" file is created in Bin folder, it would be more clean IMHO in Bin\Chrome folder

3) - very little issue - the Soft.version line in X-chromium.ini is not updated

Thank you in advance for any reply and for your script once again!

Best Regards
Nuv

**Comment by JustOff** [comment]
If you want to get portable flash installation (local dll) you should uninstall system _pepper_ flash.
