### ISSUE TITLE
Chromium script KO

### ISSUE THREAD

**Issue by Nuvolarix** [JustOff/cpf-update-win#4]
I got this error yesterday, same issue today.
Could you have a look at it?

![image1](https://cloud.githubusercontent.com/assets/15817707/14700838/3e50934c-07a2-11e6-8a9f-1ccc64460886.jpg)

Thanks in advance.

Best Regards
Nuv

**Comment by JustOff** [comment]
The fact is that Chromium team has removed few LKGR builders. More info [here](http://chromium.woolyss.com/).

Script will be updated as far as chromium.woolyss.com API will replace LKGR to the alternative stable branch.

**Comment by JustOff** [comment]
A workaround was implemented.
